CREATE TABLE Customer(
	Id		INT IDENTITY,
	[Name]	VARCHAR(50) NOT NULL,
	City	VARCHAR(50) NOT NULL,
	Phone	VARCHAR(50) NULL
	CONSTRAINT PK_Customer_Id PRIMARY KEY CLUSTERED (Id)
)
GO
CREATE TABLE [Transaction](
	Id				INT IDENTITY,
	CustId			INT NOT NULL,
	Symbol			VARCHAR(50) NOT NULL,
	NoOfShares		INT	NOT NULL,
	PurchasePrice	INT	NOT NULL,
	CONSTRAINT FK_Tran_Customer FOREIGN KEY (CustId)     
    REFERENCES Customer(Id)     
    ON DELETE CASCADE    
    ON UPDATE CASCADE,    
	CONSTRAINT PK_Transaction_Id PRIMARY KEY CLUSTERED (Id)
)
GO